#Message sent to console when command can not be run by console
console_error_message: '&8[&c*&8] &cYou are unable to execute this commmand!'

#No permission message
no_perm_message: '&e&lCEssentials &6/ &cYou do not have permission acidessentials.fly'

#FlyCMD Below
FlyCMD:
  flying_enabled: '&e&lCEssentials &6/ &7Fly has been &aenabled!'
  flying_disabled: '&e&lCEsentials &6/ &7Fly has been &cdisabled!'